const data = {
  pets: [
    {
      name: 'German Sheperd',
      slug: 'german-sheperd',
      category: 'Dogs',
      image: '/images/germansheperd.jpg',
      price: 1,
      countInShelter: 5,
      brand: 'German',
      rating: 7,
      numReviews: 2,
      description: 'responsible dog',
    },
    {
        name: 'Husky',
        slug: 'husky',
        category: 'Dogs',
        image: '/images/husky.jpg',
        price: 1,
        countInShelter: 5,
        brand: 'Husky',
        rating: 7,
        numReviews: 2,
        description: 'snow dog',
      },
      {
        name: 'Bulldog',
        slug: 'bulldog',
        category: 'Dogs',
        image: '/images/bulldog.jpg',
        price: 1,
        countInShelter: 5,
        brand: 'English',
        rating: 7,
        numReviews: 2,
        description: 'funny dog',
      },
      {
        name: 'Sausage Dog',
        slug: 'sausage-dog',
        category: 'Dogs',
        image: '/images/sausagedog.jpg',
        price: 1,
        countInShelter: 5,
        brand: 'Tiny',
        rating: 7,
        numReviews: 2,
        description: 'slinky dog',
      },
      {
        name: 'Weimeraner',
        slug: 'weimeraner',
        category: 'Dogs',
        image: '/images/weimeraner.jpg',
        price: 1,
        countInShelter: 5,
        brand: 'German',
        rating: 7,
        numReviews: 2,
        description: 'energetic dog',
      },
  ],
};

export default data;
